### ISSUE TITLE
DML Loss function

### ISSUE THREAD

**Issue by aryanasadianuoit** [SforAiDl/KD_Lib#102]
* Paper: Deep Mutual Learning
* Paper Link: 

### Description
```
Hi. According to the paper, The total loss objective should be the summation of cross-entropy and Kullback_Leibler divergence. But I found that you have used MSE loss. Is there a specific reason for it?```
### Modifications 
```
```

**Comment by Het-Shah** [comment]
Hi, There is no specific reason for us to add MSE Loss. We were playing around with the loss functions of various implementations and were testing the ability of the module to adapt to new loss functions, this is the reason it has MSE instead of CE+KL div.

**Comment by Het-Shah** [comment]
Closing this issue for now, if you still have doubts feel free to open it again!
