### ISSUE TITLE
Pip install "stable" doesn't work

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [SforAiDl/KD_Lib#108]
Running `pip install KD-Lib` does not correctly install the library and leads to import errors (tested on Colab [here](https://gist.github.com/BrunoGomesCoelho/1f8f3792a02ded4a7101de9636ba1518#file-kd-lib-test-ipynb)).

Installing manually from source does work (as #82 mentions); Maybe the README should be updated to state only manual install is working?

Regardless, thanks for the cool library!

**Comment by Het-Shah** [comment]
Thank you so much @BrunoGomesCoelho for pointing it out, and sorry for such a late reply. We will be rectifying this asap. We have been planning to bump the pypi version but I forgot to do it, sorry once again 😓

**Comment by Het-Shah** [comment]
@BrunoGomesCoelho we have updated the pip installation as well now, you can now install via `pip install KD-Lib`. Thank you once again for letting us know!

**Comment by BrunoGomesCoelho** [comment]
Cool, thanks for the update! :)
