### ISSUE TITLE
custom dataloader for NLP dataset

### ISSUE THREAD

**Issue by OriAlpha** [SforAiDl/KD_Lib#128]
I am trying this library, i can see data are loaded via dataloaders. In my case i am using for NLP model. So i have list of sentences and i have build a custom dataloader function. But when i call 
`distiller.train_student(epochs=5, plot_losses=True, save_model=True) `
it creates a issue, so any suggestions for creating custom dataloader for sentences. 
I have used this example for building dataloaders. 
https://stackoverflow.com/a/63259870.

**Comment by NeelayS** [comment]
Hi @OriAlpha.

Could you tell me what kind of NLP task you are looking to do? Also, could you please post the error stack trace if possible?

**Comment by NeelayS** [comment]
The distillation methods KD-Lib provides are designed primarily for classification tasks. Hence, the `distiller` objects expect dataloaders which supply 2 things: the input data for the classification task and a corresponding label for the task. In your case, the dataloders seem to be supplying 3 things: input data, attn masks, and labels while only 2 were expected.

**Comment by OriAlpha** [comment]
yes, thats true. After fixing this while computing the loss between teacher and student model, i see error in 
`self.calculate_kd_loss(student_out, teacher_out, label)` 
error as 
`TypeError: unsupported operand type(s) for /: 'SequenceClassifierOutput' and 'float'`

**Comment by NeelayS** [comment]
Feel free to close this if your issue has been resolved @OriAlpha.
