### ISSUE TITLE
Issue with CUDA

### ISSUE THREAD

**Issue by OriAlpha** [SforAiDl/KD_Lib#129]
I am facing issue with cuda, I have used following command to install PyTorch 
`conda install pytorch==1.8.1 torchvision==0.9.1 torchaudio==0.8.1 cudatoolkit=11.3 -c pytorch -c conda-forge `

When I try using my gpu, it fails and uses cpu as default. Error as: 
`Either an invalid device or CUDA is not available. Defaulting to CPU. `

I am following distillation example on readme

**Comment by NeelayS** [comment]
Are you sure that you have correctly installed the cudatoolkit version compatible with your GPU and other software?
Could you run the following code snipped in your Python evironment and let me know the output
```
import torch
torch.cuda.is_available()
```

**Comment by OriAlpha** [comment]
i found the issue, but thanks
