### ISSUE TITLE
No module named 'KD_Lib.KD'

### ISSUE THREAD

**Issue by Ti-Oluwanimi** [SforAiDl/KD_Lib#143]
What could be the cause of the above error after using 
```
from KD_Lib.KD import VanillaKD
```

**Comment by Het-Shah** [comment]
I can't see the error message. Can you post the error message again?

**Comment by Ti-Oluwanimi** [comment]
No module named 'KD_Lib.KD'

That could be because of the pip install

Now, I am tyrying to install from source to see if it works

**Comment by Ti-Oluwanimi** [comment]
Same error

**Comment by Het-Shah** [comment]
I am unable to reproduce this error. Can you try making a fresh environment and try installing KD_Lib?

**Comment by Ti-Oluwanimi** [comment]
kd-lib 0.0.32 requires matplotlib==3.2.1, but you have matplotlib 3.6.1 which is incompatible.
kd-lib 0.0.32 requires pip==21.1, but you have pip 22.2.2 which is incompatible.
kd-lib 0.0.32 requires wheel==0.32.1, but you have wheel 0.37.1 which is incompatible.

**Comment by Het-Shah** [comment]
Can you install the required versions in your environment? Your environment is interfered with by the package versions in your base environment. 

For example to install matplotlib==3.2.1 run `pip install matplotlib==3.2.1`

**Comment by Ti-Oluwanimi** [comment]
Yeah, I am trying that now. Cheers!

**Comment by Ti-Oluwanimi** [comment]
Great! I'm closing it now! Merci beaucoup
