### ISSUE TITLE
Paper: Paying More Attention To The Attention - Improving the Performance of CNNs via Attention Transfer

### ISSUE THREAD

**Issue by khizirsiddiqui** [SforAiDl/KD_Lib#15]
* Paper: Paying More Attention To The Attention - Improving the Performance of CNNs via Attention Transfer
* Paper Link: https://arxiv.org/pdf/1612.03928.pdf

### Description
```
The paper proposes a mechanism to transfer knowledge in form of attention (both gradient and activation based spatial attention maps). The approach provides significant increase in the performance of resnets and non-resnets.
```
### Modifications 
```
Not yet any? 
```

I have only read the abstract yet, sust to confirm, this paper lies within the KD domain, right? It seems like one of the approaches that can be used with other techniques in KD like using relational KD loss function along wit, maybe, Teacher-Assisted KD.
If this is completely different topic, please close this issue.

**Comment by Het-Shah** [comment]
Yes this is related to KD. It is somewhat similar to learning intermediate representation paper ( my issue ). The paper basically makes student learn intermediated layers rather than finaly probability distribution.
