### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by Het-Shah** [SforAiDl/KD_Lib#22]
Refactor all the following papers:
- [x] TAKD (@Het-Shah)
- [x] Attention (@Het-Shah)
- [x] Noisy (@khizirsiddiqui)

Assign yourselves. Let's get this done quickly and then we can continue adding more papers.

**Comment by khizirsiddiqui** [comment]
@NeelayS if it is okay to, I will refactor Noisy.

**Comment by NeelayS** [comment]
> @NeelayS if it is okay to, I will refactor Noisy.

Yeah, sure.
