### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by khizirsiddiqui** [SforAiDl/KD_Lib#28]
### Description
Undocumented parts:
 - Parameters to `init` of `BaseClass` are undocumented.
 - `calculate_kd_loss()` for every class other than `BaseClass`.
 - All `NoisyTeacher`, `orignal`, `attention` require params in addition to `BaseClass` params.
 - Citations to papers in classes definition (?)
 - ResNet and other Models

This is not a priority obviously, we can do them in between other new paper implementations, I guess.

**Comment by Het-Shah** [comment]
I guess we should be doing all of this as of now shouldn't take much time as well. @avishreekh, Can you take this up?

**Comment by avishreekh** [comment]
> I guess we should be doing all of this as of now shouldn't take much time as well. @avishreekh, Can you take this up?

Yes sure
