### ISSUE TITLE
Device parameter of Base class 

### ISSUE THREAD

**Issue by avishreekh** [SforAiDl/KD_Lib#33]
The Base class has a parameter `device` for choosing between CPU and GPU. However, there are a few issues with respect to this:
1. There is no check for the validity of the device specified. For example, I could specify a device "kd" which does not exist.
2. There is no check for GPU availability when "cuda" is specified as a parameter. The class should default to use CPU when cuda is not available.

**Comment by Het-Shah** [comment]
add a assert statement maybe and default it to cpu if all assert fail. How does this sound?

**Comment by avishreekh** [comment]
Ya this sounds good
