### ISSUE TITLE
Paper: Subclass Distillation

### ISSUE THREAD

**Issue by NeelayS** [SforAiDl/KD_Lib#54]
* Paper Link: https://arxiv.org/pdf/2002.03936.pdf

### Description
```
The teacher is made to divide each class into many subclasses that it invents
during the supervised training. The student is then trained to match the subclass probabilities
Intuition is that doing this provides more fine grained knowledge and helps the student learn faster.
```

**Comment by NeelayS** [comment]
Didn't think through the implementation of this paper before raising this issue. It will require access to the model definition and hence won't fit in here.

**Comment by NeelayS** [comment]
Closing this

**Comment by Bontempogianpaolo1** [comment]
Hi, thank you for your work! Sorry if I disturb you but what exactly did not allow you to implement it? I am interested precisely in this issue of transferring knowledge of sub-classes. Given your experience with "knowledge distillation", do you know similar works?

**Comment by NeelayS** [comment]
Hi @Bontempogianpaolo1!
In the library, we provide trainer classes which take in teacher and/or student models, dataloaders, and and other parameters/hyperparameters and can be used to carry out distillation. In the `Subclass Distillation` paper, the authors use "subclass heads" along with backbones of image classification models to "invent" subclasses with an aim to transfer fine-grained knowledge to student models. Since the trainer classes take in model objects from a user and do not have access to the model definition process, appending such "subclass heads" would require the trainer to make certain assumptions about the structure of the model, which we wanted to avoid. Secondly, the paper also talks about using the outputs from the penultimate layer of teacher models to perform distillation, which again would be tricky for us. For these couple of reasons, we refrained from implementing this paper in the library at that time.
