### ISSUE TITLE
Restructure text-based models and utilities

### ISSUE THREAD

**Issue by avishreekh** [SforAiDl/KD_Lib#57]
I think we should have a separate sub-directory for text models and associated utilities. What do you think @Het-Shah ?

We could look at these tasks, to begin with:

- [ ]   Add train, evaluate and distill functions for different models to `text.utils`
- [ ]   Move LSTM class to `text.models`
- [ ]   Move Bert2LSTM to `text` (after correcting the existing mistakes)

**Comment by Het-Shah** [comment]
What exactly do you mean by a separate sub-directory? 
Is it `KD_Lib->text->KD,Pruning,Quantization` or `KD_Lib->KD->text/KD_Lib->Pruning->text....`

**Comment by avishreekh** [comment]
Maybe something like `KD_Lib->text` only for the KD implementations. As Pruning is generic in the sense that it can accommodate all kinds of PyTorch models, I don't think we need to separate things there.
So maybe `KD_Lib->text->Bert2LSTM` etc.

**Comment by Het-Shah** [comment]
let's keep it like `KD_Lib->text->KD->...` for the ease of readabiliy.
