### ISSUE TITLE
Paper: Improved Knowledge Distillation via Teacher Assistant

### ISSUE THREAD

**Issue by khizirsiddiqui** [SforAiDl/KD_Lib#6]
arXiv : https://arxiv.org/pdf/1902.03393.pdf

**Comment by Het-Shah** [comment]
This is a great paper to start with. You can think of modification that you can do to this paper. A suggestion would be having multiple TA's (We don't know what the outcomes maybe but we can always experiment, might give good results). Let me know of your thoughts on this.

**Comment by Het-Shah** [comment]
You can also add your name to `CONTRIBUTORS.rst` :smile:
