### ISSUE TITLE
Paper: Sequence-Level Knowledge Distillation

### ISSUE THREAD

**Issue by avishreekh** [SforAiDl/KD_Lib#7]
Sequence-Level Knowledge Distillation, Yoon Kim, Alexander M. Rush, 2016
https://arxiv.org/pdf/1606.07947.pdf

**Comment by Het-Shah** [comment]
This is a great paper on the NLP side of things. You can later try something along these lines for transformer-based networks.

**Comment by Het-Shah** [comment]
You can add your name to `CONTRIBUTORS.rst`. :smile:

**Comment by avishreekh** [comment]
> This is a great paper on the NLP side of things. You can later try something along these lines for transformer-based networks.

I actually found an ICLR paper for transformers. Will definitely think of that after this.

**Comment by Het-Shah** [comment]
> I actually found an ICLR paper for transformers. Will definitely think of that after this.

Yup I have read that paper I guess, is it TinyBERT?
