### ISSUE TITLE
Update setup.py

### ISSUE THREAD

**Issue by NeelayS** [SforAiDl/KD_Lib#82]
The _requirements_ list which is passed into _install_requires_ in _setup()_ is empty.
It should be populated with _requirements_dev.txt_, shouldn't it ?

**Comment by Het-Shah** [comment]
Nope, I don't think so it is getting taken care of by requirements_dev.txt. Check it once by creating a new environment and installing it or installing it on colab.

**Comment by NeelayS** [comment]
Tried it out, packages in _requirements_dev.txt_ aren't installed by `python setup.py install`

**Comment by Het-Shah** [comment]
This is weird last time we tried doing this it worked. 
cc: @khizirsiddiqui

**Comment by khizirsiddiqui** [comment]
@Het-Shah I didn't test it. :sweat_smile: Daily data limits + internet speed, pytorch is expensive.

**Comment by Het-Shah** [comment]
wait I'll check on colab once.

**Comment by NeelayS** [comment]
![Screenshot from 2020-08-30 14-57-24](https://user-images.githubusercontent.com/44301912/91655820-61e9d400-ead1-11ea-94f8-1ccae4225703.png)

Why is the import failing ?

**Comment by Het-Shah** [comment]
> Tried it out, packages in requirements_dev.txt aren't installed by python setup.py install

Yea this doesn't work. @NeelayS can you solve this issue?

**Comment by Het-Shah** [comment]
> Why is the import failing ?

I am able to import it on colab as well

**Comment by NeelayS** [comment]
> Yea this doesn't work. @NeelayS can you solve this issue?

Yes, I'll do this

**Comment by youjinqing123** [comment]
When I import VanillaKD, I have the same error 'No module named   KD_Lib.KD'.
I set a new conda virtual environment (python=3.6) for your project on linux, installed all requirements according to requirements_dev.txt(e.g. torch==1.5.0, torchvision==0.6.0), then I install with 'pip install KD-Lib'. Then I met this ModuleNotFoundError. Could you please tell me how to solve this issue?

**Comment by Het-Shah** [comment]
Hi! Can you install KD_Lib from source. Basically follow these steps - 

```
pip install transformers
git clone https://github.com/SforAiDl/KD_Lib.git
cd KD_Lib
python setup.py install
```

After running these try  `from KD_Lib.KD import VanillaKD`. I hope this will work.

**Comment by eubinecto** [comment]
@Het-Shah 
> Hi! Can you install KD_Lib from source. Basically follow these steps -
> 
> ```
> pip install transformers
> git clone https://github.com/SforAiDl/KD_Lib.git
> cd KD_Lib
> python setup.py install
> ```
> 
> After running these try `from KD_Lib.KD import VanillaKD`. I hope this will work.

Hi, sorry for fussing around, but it seems installing the library from the source does not resolve the issue either :( I had a look at my virtualenv to see what's been installed, and it seems nothing have been installed, but `__init__.py`. 

<img width="811" alt="image" src="https://user-images.githubusercontent.com/56193069/106466393-9c232b80-64de-11eb-9236-79ef6a891089.png">

I suspect there is potentially something erroneous going on in `setup.py`?

**Comment by khizirsiddiqui** [comment]
Hey @eubinecto , thanks for debugging this, we are learning with package development, hopefully will sort this quick. Thanks again! :)

**Comment by khizirsiddiqui** [comment]
@eubinecto  we have fixed this on our side, please open another issue if you still face it. Thanks!
