### ISSUE TITLE
Validation on the fly and saving models according to validation accuracy

### ISSUE THREAD

**Issue by ashwinvaswani** [SforAiDl/KD_Lib#95]
Currently, validation is only done after training and it's good to have validation on the fly as it gives a better understanding of over / underfitting of the model. Moreover, models are saved on the basis of training metrics and not validation metrics currently.

**Comment by Het-Shah** [comment]
Yea i think we should be taking in a val loader as well in the `__init__`. Great, we surely missed this small error!

**Comment by avishreekh** [comment]
Can I take this up? Thanks!

**Comment by Het-Shah** [comment]
Yea go ahead :)
